### PR TITLE
Fix contributor list, add kredits service tests

### LINKED ISSUE #114: Contributor not showing up in toplist
Currently I am not showing up in the contributor list though I have 7500 kredits earned (and a 298 kredits balance). 

I currently do not have any unconfirmed contributions. 
This line makes me wonder if contributors without unconfirmed contributions get lost: https://github.com/67P/kredits-web/blob/master/app/services/kredits.js#L49

### PR DESCRIPTION
**Pull request by skddc**
closes #114

### CODE REVIEW

File: app/services/kredits.js [hunk 1]
```diff
@@ -46,18 +46,33 @@ export default Service.extend({
   }),
 
   kreditsByContributor: computed('contributionsUnconfirmed.[]', 'contributors', function() {
```
Comment (galfert) [inline app/services/kredits.js]: I think you might want to change the dependency, so the computed property updates when the `vetoed` status of any of the contributions changes.

```suggestion
  kreditsByContributor: computed('contributionsUnconfirmed.@each.vetoed', 'contributors', function() {
```

Comment (skddc) [reply app/services/kredits.js]: Cool. Will that still account for new objects in the collection, and changes of other properties?

Comment (galfert) [reply app/services/kredits.js]: Yes, it will also update when the array itself changes (e.g. elements added or removed). If you want to add additional properties as dependencies, you would add them like this `contributionsUnconfirmed.@each.{vetoed,otherProperty}`.
